// ============================================================
// GerhartStudios — Satirical Content Data
// All metrics, reviews, and content are fictional parody.
// ============================================================

export interface SlopMetric {
  id: string;
  label: string;
  value: number;
  tag: string;
  gradientFrom: string;
  gradientTo: string;
  glowColor: string;
  description: string;
}

export interface PipelineStep {
  step: number;
  emoji: string;
  title: string;
  description: string;
  tag: string;
  borderColor: string;
  bgColor: string;
  tagBg: string;
  tagText: string;
}

export interface Review {
  id: number;
  name: string;
  role: string;
  avatar: string;
  stars: number;
  text: string;
}

export interface MemeCard {
  id: number;
  topText: string;
  bottomText: string;
  subText?: string;
  emoji: string;
  style: 'purple' | 'cyan' | 'orange' | 'pink' | 'green' | 'red';
}

export interface FAQItem {
  q: string;
  a: string;
}

// ─── AI SLOP METRICS (fictional parody analytics) ────────────────────────────
export const slopMetrics: SlopMetric[] = [
  {
    id: 'prompt-ratio',
    label: 'Prompt-to-Code Ratio',
    value: 94,
    tag: 'critically vibed',
    gradientFrom: '#a855f7',
    gradientTo: '#9333ea',
    glowColor: 'rgba(168,85,247,0.6)',
    description: 'Lines authored via prompt vs. actual human typing. The 6% was a typo.',
  },
  {
    id: 'hallucinations',
    label: 'Hallucinations per Commit',
    value: 87,
    tag: 'artisanally autogenerated',
    gradientFrom: '#22d3ee',
    gradientTo: '#0891b2',
    glowColor: 'rgba(34,211,238,0.6)',
    description: 'APIs that may or may not exist, shipped with divine confidence.',
  },
  {
    id: 'claude-dependency',
    label: 'Claude Dependency Level',
    value: 99.1,
    tag: 'prompt-saturated',
    gradientFrom: '#fb923c',
    gradientTo: '#ea580c',
    glowColor: 'rgba(251,146,60,0.6)',
    description: 'Measured in "how many Claude tabs are open right now." Answer: all of them.',
  },
  {
    id: 'manual-resistance',
    label: 'Manual Coding Resistance',
    value: 96,
    tag: 'human override: denied',
    gradientFrom: '#f472b6',
    gradientTo: '#db2777',
    glowColor: 'rgba(244,114,182,0.6)',
    description: 'Likelihood of touching a keyboard without AI assistance in the loop.',
  },
  {
    id: 'untested-confidence',
    label: 'Untested Confidence Score',
    value: 100,
    tag: 'peak delusion achieved',
    gradientFrom: '#4ade80',
    gradientTo: '#16a34a',
    glowColor: 'rgba(74,222,128,0.6)',
    description: 'How confident we are vs. our actual test coverage (2%). Both are valid metrics.',
  },
  {
    id: 'human-oversight',
    label: 'Human Oversight',
    value: 2,
    tag: 'human oversight optional',
    gradientFrom: '#ef4444',
    gradientTo: '#b91c1c',
    glowColor: 'rgba(239,68,68,0.6)',
    description: 'This metric exists only to make the dashboard look balanced.',
  },
];

// ─── PIPELINE STEPS ───────────────────────────────────────────────────────────
export const pipelineSteps: PipelineStep[] = [
  {
    step: 1,
    emoji: '🌙',
    title: 'Have a Random Idea at 3am',
    description:
      'Minecraft economy plugin but what if it had vibes? Written in Notes.app before it evaporates. Marked as "TODO: ship this."',
    tag: 'ideation phase',
    borderColor: 'border-purple-500',
    bgColor: 'bg-purple-500/10',
    tagBg: 'bg-purple-500/20',
    tagText: 'text-purple-300',
  },
  {
    step: 2,
    emoji: '🤖',
    title: 'Open Claude and Send One Message',
    description:
      '"make me a minecraft economy plugin in java with enterprise support and make it good" — actual recorded prompt, actual commit message.',
    tag: 'architecture phase',
    borderColor: 'border-cyan-500',
    bgColor: 'bg-cyan-500/10',
    tagBg: 'bg-cyan-500/20',
    tagText: 'text-cyan-300',
  },
  {
    step: 3,
    emoji: '👀',
    title: 'Receive 900 Lines. Accept Blindly.',
    description:
      'If the AI was confident, who are you to doubt it? Scroll to bottom, see no red squiggles, commit. This is what seniors do.',
    tag: 'code review™',
    borderColor: 'border-orange-500',
    bgColor: 'bg-orange-500/10',
    tagBg: 'bg-orange-500/20',
    tagText: 'text-orange-300',
  },
  {
    step: 4,
    emoji: '⌨️',
    title: 'Rename Two Variables',
    description:
      'Changed `temp` to `data` and `data` to `result`. This is refactoring. Human contribution: exactly 0.3%.',
    tag: 'engineering',
    borderColor: 'border-yellow-500',
    bgColor: 'bg-yellow-500/10',
    tagBg: 'bg-yellow-500/20',
    tagText: 'text-yellow-300',
  },
  {
    step: 5,
    emoji: '⚙️',
    title: 'Write config.yml by Hand',
    description:
      '47 nested YAML keys. None documented. All optional. This is the only file humans touched. It is 800 lines.',
    tag: 'configuration',
    borderColor: 'border-green-500',
    bgColor: 'bg-green-500/10',
    tagBg: 'bg-green-500/20',
    tagText: 'text-green-300',
  },
  {
    step: 6,
    emoji: '🏆',
    title: 'Declare It "Enterprise Ready"',
    description:
      'Add "enterprise", "production-grade", and "battle-tested" to the README. It has run once. Locally. With no players connected.',
    tag: 'marketing dept.',
    borderColor: 'border-pink-500',
    bgColor: 'bg-pink-500/10',
    tagBg: 'bg-pink-500/20',
    tagText: 'text-pink-300',
  },
  {
    step: 7,
    emoji: '🚀',
    title: 'Ship to Production',
    description:
      'git push origin main with the energy of someone who has never heard the phrase "staging environment." We move fast.',
    tag: 'deployment',
    borderColor: 'border-blue-500',
    bgColor: 'bg-blue-500/10',
    tagBg: 'bg-blue-500/20',
    tagText: 'text-blue-300',
  },
  {
    step: 8,
    emoji: '🙏',
    title: 'Open Support Ticket and Pray',
    description:
      '"Works on my machine" resolves the ticket. User is still experiencing the issue. This is called customer success.',
    tag: 'customer success',
    borderColor: 'border-red-500',
    bgColor: 'bg-red-500/10',
    tagBg: 'bg-red-500/20',
    tagText: 'text-red-300',
  },
];

// ─── FAKE REVIEWS (clearly satirical, fictional, not real) ───────────────────
export const reviews: Review[] = [
  {
    id: 1,
    name: 'Notch H.',
    role: 'CEO, BlockCorp™ (fictional)',
    avatar: '🧱',
    stars: 5,
    text: "I installed one plugin and suddenly my server had a business model. I didn't ask for this. I'm not complaining.",
  },
  {
    id: 2,
    name: 'SteveXX_Pro',
    role: 'Professional Minecrafter, Totally Real Inc.',
    avatar: '⛏️',
    stars: 5,
    text: "The code compiled, the economy inflated, and my life changed. I don't understand any of it. Five stars.",
  },
  {
    id: 3,
    name: 'xXDeadpoolXx',
    role: 'Senior Donut Engineer',
    avatar: '🍩',
    stars: 5,
    text: "I asked for one feature and received a complete theological framework. The config.yml is 800 lines. I've accepted this.",
  },
  {
    id: 4,
    name: 'CraftyDev_69',
    role: 'Principal Vibe Architect',
    avatar: '🎯',
    stars: 5,
    text: "You can literally smell the vibecoding through the config. Every method is 'handleThing' or 'processStuff'. Peak engineering.",
  },
  {
    id: 5,
    name: 'GrumpyAdmin2077',
    role: 'Has Not Slept Since 2022',
    avatar: '😤',
    stars: 5,
    text: "Zero documentation. Seven undocumented APIs. Plugin calls home to an IP I can't identify. 10/10 would install again.",
  },
  {
    id: 6,
    name: 'Pr0_Gamer_Zero',
    role: 'Self-Certified Prompt Engineer',
    avatar: '🎮',
    stars: 5,
    text: "I read the source code and started seeing colors. My doctor said this was probably fine. The vibes are too powerful.",
  },
];

// ─── MEME CARDS (original satirical content, no copyrighted assets) ───────────
export const memeCards: MemeCard[] = [
  {
    id: 1,
    topText: 'ME:',
    bottomText: '"just a quick plugin, won\'t take long"',
    subText: '[900 unreviewed lines later] "shipped"',
    emoji: '😅',
    style: 'purple',
  },
  {
    id: 2,
    topText: 'SHIPS TO PRODUCTION',
    bottomText: 'with 0 unit tests',
    subText: '"it compiled on my machine" — closes ticket',
    emoji: '🚀',
    style: 'red',
  },
  {
    id: 3,
    topText: '"This isn\'t AI slop"',
    bottomText: '"it\'s artisanally autogenerated"',
    subText: '— GerhartStudios, probably',
    emoji: '🎨',
    style: 'cyan',
  },
  {
    id: 4,
    topText: 'DONUTPLUGINS CODE REVIEW:',
    bottomText: '"lgtm"',
    subText: '— nobody reviewed it. not a single soul.',
    emoji: '✅',
    style: 'green',
  },
  {
    id: 5,
    topText: 'VIBECODING IS NOT A CRY FOR HELP',
    bottomText: 'it is a software methodology',
    subText: '(it is absolutely a cry for help)',
    emoji: '💡',
    style: 'orange',
  },
  {
    id: 6,
    topText: 'WHEN CLAUDIA HALLUCINATES AN API',
    bottomText: 'and you ship it anyway',
    subText: '"the confidence to not check the docs is a gift"',
    emoji: '🔮',
    style: 'pink',
  },
];

// ─── FAQ ITEMS ─────────────────────────────────────────────────────────────────
export const faqs: FAQItem[] = [
  {
    q: 'Is this website serious?',
    a: "No. This is a satire/parody website created for humor and chaotic internet energy. Nothing here constitutes factual reporting, verified analysis, or professional advice of any kind. If you thought any of the metrics were real, we're both concerned and flattered.",
  },
  {
    q: 'Are the DonutPlugins actually AI generated?',
    a: "With the measured confidence of someone who has never run a unit test: we have absolutely no idea. The satirical AI Slop Meter™ is entirely fictional. Any resemblance to actual code quality metrics, real or imagined, is coincidental and possibly a cry for help.",
  },
  {
    q: 'Who is Claudia?',
    a: "Claudia is a fictional Chief Vibe Architecture Officer — a parody character inspired by large language models and dev culture. She is not a real person, not affiliated with Anthropic or any real organization, and cannot be held legally responsible for your production incidents.",
  },
  {
    q: 'Is vibecoding a software methodology or a cry for help?',
    a: 'Yes.',
  },
  {
    q: 'Can I trust this brand?',
    a: "We maintain a 98% uptime on trust, meaning we've been trustworthy for approximately 7 hours this calendar year. Our trust score is calculated by a proprietary algorithm (a random number generator with a purple gradient applied to it). So: no. Absolutely not. That's the bit.",
  },
  {
    q: 'Is this affiliated with any real plugin developer?',
    a: "This is a satirical parody project. Any references to real projects, plugins, or developers are used for parody purposes, are clearly exaggerated, and should not be interpreted as factual claims or verified reporting. This is not journalism. This is a meme website with SEO.",
  },
  {
    q: 'What exactly is a DonutPlugin?',
    a: "Allegedly: a Minecraft plugin. In practice: a YAML file surrounded by vibes and 900 lines of unreviewed Java. Spiritually: a donut — mostly hollow, somehow delicious, and you're never quite sure what's inside.",
  },
  {
    q: 'Should I base any real decisions on this website?',
    a: "Under no circumstances whatsoever. This website exists for humor. The metrics are fake. The reviews are satirical. The AI Slop Meter is not a real measurement tool. Please do not make software decisions, hiring decisions, or life decisions based on anything you read here.",
  },
];
