import { useEffect, useRef, useState } from "react";
import { Activity, Gauge, Cpu, ShieldOff, Zap, HelpCircle } from "lucide-react";

const metrics = [
  { label: "Prompt-to-Code Ratio", value: 97, tag: "critically vibed", icon: Gauge },
  { label: "Hallucinations per Commit", value: 84, tag: "autogenerated", icon: Activity },
  { label: "Claude Dependency Level", value: 99, tag: "prompt-saturated", icon: Cpu },
  { label: "Manual Coding Resistance", value: 92, tag: "human optional", icon: ShieldOff },
  { label: "Untested Confidence Score", value: 100, tag: "maximum hubris", icon: Zap },
  { label: "Stack Overflow Visits", value: 3, tag: "we have Claude", icon: HelpCircle },
];

const GaugeBar = ({ label, value, tag, icon: Icon }: typeof metrics[0]) => {
  const [visible, setVisible] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.3 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  return (
    <div ref={ref} className="glass-card p-4 rounded-lg">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <Icon className="w-3.5 h-3.5 text-primary" />
          <span className="text-sm text-foreground">{label}</span>
        </div>
        <span className="text-[10px] font-mono text-muted-foreground px-1.5 py-0.5 rounded bg-muted">{tag}</span>
      </div>
      <div className="w-full h-2 rounded-full bg-muted overflow-hidden">
        <div
          className="h-full rounded-full bg-primary transition-all duration-1000 ease-out"
          style={{ width: visible ? `${value}%` : "0%" }}
        />
      </div>
      <div className="text-right mt-1">
        <span className="text-xs font-mono text-primary">{value}%</span>
      </div>
    </div>
  );
};

const SlopMeter = () => (
  <section id="slop-meter" className="py-16 sm:py-24">
    <div className="container mx-auto">
      <div className="text-center mb-12">
        <span className="text-xs font-mono px-2.5 py-1 rounded glass-card text-primary mb-3 inline-block">CLASSIFIED ANALYSIS</span>
        <h2 className="text-2xl sm:text-4xl font-bold mb-3 text-foreground">AI Slop Meter</h2>
        <p className="text-sm text-muted-foreground max-w-md mx-auto">
          Our proprietary (fictional) analysis of how much AI slop resides within DonutPlugins. These numbers are 100% made up.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-3xl mx-auto">
        {metrics.map((m) => <GaugeBar key={m.label} {...m} />)}
      </div>

      <div className="text-center mt-8">
        <div className="inline-flex items-center gap-2 glass-card px-4 py-2 rounded-lg">
          <Activity className="w-4 h-4 text-primary" />
          <span className="text-sm font-mono text-muted-foreground">
            Overall Slop Index: <span className="text-primary font-semibold">CATASTROPHIC</span>
          </span>
        </div>
      </div>
    </div>
  </section>
);

export default SlopMeter;
